packages:
  - ./docs/
  - "./packages/*"
  - "./playgrounds/*"

catalog:
  nuxt: "^4.0.0-alpha.2"
  "@nuxt/kit": "^4.0.0-alpha.2"
  "@nuxt/schema": "^4.0.0-alpha.2"
  "@nuxt/ui": "^3.2.0"
  vue: latest

onlyBuiltDependencies:
  - better-sqlite3
