packages:
  - ./docs/
  - "./packages/*"
  - "./playgrounds/*"

catalog:
  nuxt: "^4.2.2"
  "@nuxt/kit": "^4.2.2"
  "@nuxt/schema": "^4.2.2"
  "@nuxt/ui": "^4.1.0"
  vue: latest

onlyBuiltDependencies:
  - better-sqlite3
