packages:
  - ./docs/
  - ./packages/*
  - ./playgrounds/*

catalog:
  '@nuxt/kit': ^4.6.0
  '@nuxt/schema': ^4.6.0
  '@nuxt/ui': ^4.11.0
  nuxt: ^4.6.0
  vue: latest

onlyBuiltDependencies:
  - better-sqlite3
