packages:
  - ./docs/
  - "./packages/*"
  - "./playgrounds/*"

catalog:
  nuxt: "^3.17.4"
  "@nuxt/kit": "^3.17.4"
  "@nuxt/schema": "^3.17.4"
  "@nuxt/ui": "^3.1.3"
  vue: latest

onlyBuiltDependencies:
  - better-sqlite3
