packages:
  - ./docs/
  - ./packages/*
  - ./playgrounds/*

catalog:
  '@nuxt/kit': ^4.2.1
  '@nuxt/schema': ^4.2.2
  '@nuxt/ui': ^4.3.0
  nuxt: ^4.2.2
  vue: ^3.5.26

onlyBuiltDependencies:
  - better-sqlite3
