packages:
  - ./docs/
  - ./packages/*
  - ./playgrounds/*

catalog:
  '@nuxt/kit': ^4.5.1
  '@nuxt/schema': ^4.5.1
  '@nuxt/ui': ^4.10.0
  nuxt: ^4.5.1
  vue: latest

onlyBuiltDependencies:
  - better-sqlite3
