/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UAccordion: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.26.10_change-case@5.4.4_db0@0.3.1_better-sqlite3@11.9.1__74e16b93b086ec0c3c8def6acb05b83a/node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue')['default']
    UAlert: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.26.10_change-case@5.4.4_db0@0.3.1_better-sqlite3@11.9.1__74e16b93b086ec0c3c8def6acb05b83a/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.26.10_change-case@5.4.4_db0@0.3.1_better-sqlite3@11.9.1__74e16b93b086ec0c3c8def6acb05b83a/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.26.10_change-case@5.4.4_db0@0.3.1_better-sqlite3@11.9.1__74e16b93b086ec0c3c8def6acb05b83a/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.26.10_change-case@5.4.4_db0@0.3.1_better-sqlite3@11.9.1__74e16b93b086ec0c3c8def6acb05b83a/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCarousel: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.26.10_change-case@5.4.4_db0@0.3.1_better-sqlite3@11.9.1__74e16b93b086ec0c3c8def6acb05b83a/node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue')['default']
    ULinkBase: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.26.10_change-case@5.4.4_db0@0.3.1_better-sqlite3@11.9.1__74e16b93b086ec0c3c8def6acb05b83a/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    UPagination: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.26.10_change-case@5.4.4_db0@0.3.1_better-sqlite3@11.9.1__74e16b93b086ec0c3c8def6acb05b83a/node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
    UStepper: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.26.10_change-case@5.4.4_db0@0.3.1_better-sqlite3@11.9.1__74e16b93b086ec0c3c8def6acb05b83a/node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
